# numpy

In [1]:
import numpy as np

In [2]:
rang = np.arange(20)
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
rang = rang.reshape(4, 5)
rang

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
print("shape => " + str(rang.shape))
print("ndim  => " + str(rang.ndim))
print("size  => " + str(rang.size))
print("dtype => " + str(rang.dtype))

shape => (4, 5)
ndim  => 2
size  => 20
dtype => int64


In [23]:
np.zeros((4, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.ones((5, 9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# lets Go

In [25]:
first = np.array([2, 3, 4, 5, 6, 7])
first

array([2, 3, 4, 5, 6, 7])

In [27]:
second = np.arange(6)
second

array([0, 1, 2, 3, 4, 5])

In [28]:
first + second

array([ 2,  4,  6,  8, 10, 12])

In [30]:
result = first * second
result

array([ 0,  3,  8, 15, 24, 35])

In [31]:
result > 20

array([False, False, False, False,  True,  True])

# Pandas

In [32]:
import pandas as pd

In [35]:
pd.Series([1, 2, 3, 4, 5, "ali", "ahmadi", True, np.arange(3), np.nan])

0            1
1            2
2            3
3            4
4            5
5          ali
6       ahmadi
7         True
8    [0, 1, 2]
9          NaN
dtype: object

In [37]:
dates = pd.date_range("20210101", periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [39]:
np.random.randn(4, 4)

array([[-0.59296733, -0.70351238, -0.25985242, -0.80946679],
       [ 0.09949013,  0.63132444,  0.25793687, -0.20382003],
       [-0.57245721, -1.00584223,  0.06402541,  0.45044397],
       [-0.21296252, -0.52161371, -1.33286978, -1.0847296 ]])

In [42]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["A", "B", "C", "D"])
df

A         B         C         D
2021-01-01 -2.015089  0.533308  0.094370 -0.914220
2021-01-02 -0.874027 -1.187229  0.414016 -0.411881
2021-01-03 -0.079994 -0.795698 -0.446518 -0.930519
2021-01-04  0.486644 -0.511316 -0.523567  0.407341
2021-01-05  1.340189 -0.387469 -0.903693  0.494394
2021-01-06 -0.681686 -0.670161 -0.340497 -1.138473

In [43]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [44]:
df["C"]

2021-01-01    0.094370
2021-01-02    0.414016
2021-01-03   -0.446518
2021-01-04   -0.523567
2021-01-05   -0.903693
2021-01-06   -0.340497
Freq: D, Name: C, dtype: float64

In [45]:
df.head(2)

A         B         C         D
2021-01-01 -2.015089  0.533308  0.094370 -0.914220
2021-01-02 -0.874027 -1.187229  0.414016 -0.411881

In [46]:
df.tail(2)

A         B         C         D
2021-01-05  1.340189 -0.387469 -0.903693  0.494394
2021-01-06 -0.681686 -0.670161 -0.340497 -1.138473

In [47]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.303994 -0.503094 -0.284315 -0.415560
std    1.163964  0.577778  0.469341  0.712972
min   -2.015089 -1.187229 -0.903693 -1.138473
25%   -0.825942 -0.764314 -0.504305 -0.926445
50%   -0.380840 -0.590738 -0.393508 -0.663050
75%    0.344984 -0.418430 -0.014347  0.202535
max    1.340189  0.533308  0.414016  0.494394

In [48]:
df.mean()

A   -0.303994
B   -0.503094
C   -0.284315
D   -0.415560
dtype: float64

In [49]:
df.T

2021-01-01  2021-01-02  2021-01-03  2021-01-04  2021-01-05  2021-01-06
A   -2.015089   -0.874027   -0.079994    0.486644    1.340189   -0.681686
B    0.533308   -1.187229   -0.795698   -0.511316   -0.387469   -0.670161
C    0.094370    0.414016   -0.446518   -0.523567   -0.903693   -0.340497
D   -0.914220   -0.411881   -0.930519    0.407341    0.494394   -1.138473

In [50]:
df

A         B         C         D
2021-01-01 -2.015089  0.533308  0.094370 -0.914220
2021-01-02 -0.874027 -1.187229  0.414016 -0.411881
2021-01-03 -0.079994 -0.795698 -0.446518 -0.930519
2021-01-04  0.486644 -0.511316 -0.523567  0.407341
2021-01-05  1.340189 -0.387469 -0.903693  0.494394
2021-01-06 -0.681686 -0.670161 -0.340497 -1.138473

In [51]:
df.sort_values(by="C")

A         B         C         D
2021-01-05  1.340189 -0.387469 -0.903693  0.494394
2021-01-04  0.486644 -0.511316 -0.523567  0.407341
2021-01-03 -0.079994 -0.795698 -0.446518 -0.930519
2021-01-06 -0.681686 -0.670161 -0.340497 -1.138473
2021-01-01 -2.015089  0.533308  0.094370 -0.914220
2021-01-02 -0.874027 -1.187229  0.414016 -0.411881

In [52]:
df.sort_values(by="A")

A         B         C         D
2021-01-01 -2.015089  0.533308  0.094370 -0.914220
2021-01-02 -0.874027 -1.187229  0.414016 -0.411881
2021-01-06 -0.681686 -0.670161 -0.340497 -1.138473
2021-01-03 -0.079994 -0.795698 -0.446518 -0.930519
2021-01-04  0.486644 -0.511316 -0.523567  0.407341
2021-01-05  1.340189 -0.387469 -0.903693  0.494394

In [53]:
df[df["D"] > 0]

A         B         C         D
2021-01-04  0.486644 -0.511316 -0.523567  0.407341
2021-01-05  1.340189 -0.387469 -0.903693  0.494394

In [54]:
df[df["A"] <= 0]

A         B         C         D
2021-01-01 -2.015089  0.533308  0.094370 -0.914220
2021-01-02 -0.874027 -1.187229  0.414016 -0.411881
2021-01-03 -0.079994 -0.795698 -0.446518 -0.930519
2021-01-06 -0.681686 -0.670161 -0.340497 -1.138473

In [ ]:
df.read_csv("test.csv")

In [55]:
df.to_csv("test.csv")